In [4]:
import numpy as np

In [ ]:
'''
# numpy : 고성능 과학(수치)계산을 위한 데이터분석(수치분석) 패키지
     - 벡터 산술연산
     - 다차원 배열 (ndarray)
     - 표준 수학 함수
     - 선형대수, 난수
     
# numpy 배열 : 같은 종류의 데이터를 담는 자료형 (동일한 타입의 값)
 - rank : 배열 차원 (ndim)
 - shape : 각 차원 크기를 튜플로 리턴 (행, 열)
 - dtype : 배열에 저장된 자료를 알려주는 객체

# ndarray : 다차원 배열 객체
 - array()  : 배열 생성
 - arange() : 배열 생성 시 지정 값까지 자동 생성
 - reshape() : 배열 모양 변경
 - zeros() : 0이 들어있는 배열 생성
 - ones() : 1이 들어 있는 배열 생성
 - full() : 모든 값이 특정 상수인 배열을 생성
 - eye() : 단위 행렬 생성
 
'''

In [ ]:
import numpy as np

In [6]:
# rank가 1인 배열을 생성

a = np.array([1, 2, 3])
b = [1, 2, 3]

print(a)
print(b)

[1 2 3]
[1, 2, 3]


In [7]:
print(type(a))
print(type(b))

<class 'numpy.ndarray'>
<class 'list'>


In [8]:
a.shape

(3,)

In [9]:
a.ndim

1

In [14]:
# 2차원 배열을 생성
b = np.array([[1, 2, 3],[4, 5, 6]])
b


array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
b.dtype

dtype('int32')

In [16]:
a.dtype               # 배열에 저장된 자료의 type

dtype('int32')

In [17]:
a.itemsize            # 각 배열 요소가 메모리 상에 차지하고 있는 크기 : 보통 int는 4byte ...

4

In [18]:
arr = np.arange(12)       # arange : 0부터 시작임에 유의
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [19]:
# 3행 4열 형태로 만들기
arr = np.arange(12).reshape(3, 4); arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [20]:
arr.reshape(-1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [21]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [22]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [23]:
np.full((3, 3), 10)

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [24]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
# 활용 - 임의의 데이터가 필요할 때
np.random.random((2, 2))

array([[0.98461018, 0.33887783],
       [0.92722097, 0.26544198]])

In [ ]:
'''
# 배열 인덱싱
 - 슬라이싱 : 파이썬 리스트를 다루는 것과 유사하게 numpy에서도 슬라이싱이 가능
            : 슬라이싱된 배열은 원본 배열과 같은 데이터를 참조함. 그러므로 슬라이싱 된 배열을 수정하면 원본 배열도 수정이 됨
            : numpy 배열을 슬라이싱하면 그 결과는 언제나 원본 배열의 부분 배열임.
            
 - 인덱싱 : numpy 배열 인덱싱은 팬시 인덱싱(fancy indexing)이라고도 함.
          : 배열 인덱싱의 유용한 기능 중 하나가 행렬의 각 행에서 하나의 요소를 선택하거나 바꾸는 기능
          
'''

In [26]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [27]:
# 1, 2, 5, 6을 가져오고 싶음.
b = a[:2,:2]; b

array([[1, 2],
       [5, 6]])

In [38]:
# (2, 3, 6, 7) 을 가져오고 싶음
c = a[:2, 1:3]; c

array([[2, 3],
       [6, 7]])

In [39]:
# 인덱싱
b[0, 0]
print('---------------')
print(b[0, 0])

1

In [40]:
b[0, 0] = 100; b

array([[100,   2],
       [  5,   6]])

In [41]:
a      # a 원본 배열을 잘라간 b 부분배열을 수정하면 원본 배열인 a에도 영향을 미침에 유의!

array([[100,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12]])

In [42]:
# (5, 6, 7, 8)을 가져오기
d = a[1, :]; d

array([5, 6, 7, 8])

In [46]:
print(d.ndim)
print(d.shape)

1
(4,)


In [47]:
# (2, 5, 10)을 가져오기
e = a[:, 1]; e

array([ 2,  6, 10])

In [49]:
print(e.ndim)
print(e.shape)

1
(3,)


In [50]:
# (2, 6, 10)을 열 형태로 가져오기
f = a[:, 1:2]; f

array([[ 2],
       [ 6],
       [10]])

In [51]:
print(f.ndim)
print(f.shape)

2
(3, 1)


In [52]:
# 리스트를 이용하여 원하는 행과 열을 각각 짝지어서 가져오기
a = np.array([[1, 2], [3, 4], [5, 6]]); a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [53]:
a[[0, 1, 2], [0, 1, 0]]

array([1, 4, 5])

In [54]:
b = a[[0, 1, 2], [0, 1, 0]]; b

array([1, 4, 5])

In [55]:
b.shape

(3,)

In [57]:
# 정수 인덱싱
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9]); a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
idx = np.array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2]); idx

array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2])

In [60]:
a[idx]

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3])

In [61]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# 부울 인덱싱

In [63]:
a = np.array([[1, 2], [3, 4], [5, 6]]); a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [64]:
g = a[:, [True, False]]; g      # 가져오고 싶은 열을 True

array([[1],
       [3],
       [5]])

In [65]:
g.shape

(3, 1)

In [ ]:
'''
# 배열 연산
 - 기본은 배열의 각 요소별로 동작.
 - 수학함수, 연산자, numpy 함수 모듈을 통해 배열 연산이 가능
'''

In [66]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])

In [67]:
print(x)
print(y)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [68]:
x + y 

array([[ 6,  8],
       [10, 12]])

In [69]:
np.add(x, y)

array([[ 6,  8],
       [10, 12]])