In [10]:
import numpy as np

In [ ]:
'''
# numpy : 고성능 과학(수치) 계산을 위한 데이터분석(수치분석) 패키지
        - 벡터 산술연산
        - 다차원 배열 (ndarray)
        - 표준 수학 함수
        - 선형대수, 난수

# numpy 배열 : 같은 종류의 데이터를 담는 자료형 (동일한 타입의 값)
 - rank : 배열 차원 (ndim)
 - shape : 각 차원 크기를 튜플로 리턴 (행, 열)
 - dtype : 배열에 저장된 자료를 알려주는 객체
 
# ndarray : 다차원 배열 객체
 - array() : 배열 생성 
 - arange() : 배열 생성 시 지정 값까지 자동 생성
 - reshape() : 배열 모양 변경
 - zeros() : 0이 들어있는 배열 생성
 - ones() : 1이 들어있는 배열 생성
 - full() : 모든 값이 특정 상수인 배열을 생성
 - eye() : 단위 행렬 생성

'''

In [ ]:
import numpy as np

In [2]:
# rank가 1인 배열을 생성

a = np.array([1, 2, 3])
b = [1, 2, 3]
print(a)
print(b)


[1 2 3]
[1, 2, 3]


In [4]:
print(type(a))
print(type(b))

<class 'numpy.ndarray'>
<class 'list'>


In [5]:
a.shape

(3,)

In [7]:
a.ndim

1

In [9]:
# 2차원 배열을 생성
b = np.array([[1, 2, 3],[4, 5, 6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
b.dtype

dtype('int32')

In [11]:
a.dtype           # 배열에 저장된 자료의 type

dtype('int32')

In [12]:
a.itemsize        # 각 배열 요소가 메모리 상에 차지하고 있는 크기 : 보통 int는 4byte ...

4

In [14]:
arr = np.arange(12)    # arange : 0부터 시작임에 유의
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [15]:
arr = np.arange(12); arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [27]:
# 3행 4열 형태로 만들기
arr = np.arange(12).reshape(3, 4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [28]:
arr.reshape(-1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [30]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [33]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [35]:
np.full((3, 3), 10)

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [36]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [38]:
# 활용 - 임의의 데이터가 필요할 때
np.random.random((2, 2))

array([[0.62818555, 0.82331666],
       [0.6185556 , 0.65074   ]])

In [ ]:
'''
# 배열 인덱싱
 - 슬라이싱 : 파이선 리스트를 다루는 것과 유사하게 numpy에서도 슬라이싱이 가능
           : 슬라이싱된 배열은 원본 배열과 같은 데이터를 참조함. 그러므로 슬라이싱 된 배열을 수정하면 원본 배열도 수저
           : numpy 배열을 슬라이싱하면 그 결과는 언제나 원본 배열의 부분 배열임. 
 - 인덱싱 : numpy 배열 인덱싱은 팬시 인덱싱(fancy indexing)이라고도 함.
         : 배열 인덱싱의 유용한 기능 중 하나가 행렬의 각 행에서 하나의 요소를 선택하거나 바꾸는 기능
         : 정수 배열 인덱싱을 하는 경우는 원본과 다른 배열을 만들 수 있다.
'''

In [44]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [46]:
# (1, 2, 5, 6) 을 가져오고 싶음
b = a[:2,:2]; b

array([[1, 2],
       [5, 6]])

In [56]:
# (2, 3, 6, 7) 을 가져오고 싶음
c = a[:2, 1:3]; c

array([[2, 3],
       [6, 7]])

In [61]:
# 인덱싱
print(b)
print('------------')
b[0, 0]

[[100   2]
 [  5   6]]
------------


100

In [59]:
b[0, 0] = 100; b

array([[100,   2],
       [  5,   6]])

In [ ]:
a   # a 원본 배열을 잘라간 b 부분 배열을 수정하면 원본 배열인 a에도 영향을 미침에 유의!

In [63]:
# (5, 6, 7, 8)을 가져오기  => 2번째 행을 가져오기
d = a[1, :] ; d

array([5, 6, 7, 8])

In [67]:
print(d.ndim)
print(d.shape)

1
(4,)


In [68]:
# (2, 6, 10)을 가져오기   => 2번째 열을 가져오기
e = a[:, 1]; e

array([ 2,  6, 10])

In [69]:
print(e.ndim)
print(e.shape)

1
(3,)


In [72]:
# (2, 6, 10) 을 열 형태로 가져오기
f = a[:, 1:2]; f

array([[ 2],
       [ 6],
       [10]])

In [73]:
print(f.ndim)
print(f.shape)

2
(3, 1)


In [74]:
# 리스트를 이용하여 원하는 행과 열을 각각 짝지어서 가져오기
a = np.array([[1,2], [3,4], [5,6]]); a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [79]:
a[[0, 1, 2], [0, 1, 0]]

array([1, 4, 5])

In [80]:
b = a[[0, 1, 2], [0, 1, 0]]; b

array([1, 4, 5])

In [81]:
b.shape

(3,)

In [82]:
# 정수 인덱싱
a = np.array([1, 2, 3, 4, 5 ,6, 7, 8, 9]); a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [84]:
idx = np.array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2]); idx

array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2])

In [85]:
a[idx]

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3])

In [86]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [87]:
# 부울 인덱싱 
a = np.array([[1, 2], [3, 4], [5, 6]]); a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [88]:
g = a[:, [True, False]]; g  # 가져오고 싶은 열을 True

array([[1],
       [3],
       [5]])

In [89]:
g.shape

(3, 1)

In [ ]:
'''
# 배열 연산
 - 기본은 배열의 각 요소별로 동작
 - 수학함수, 연산자, numpy 함수 모듈을 통해 배열 연산이 가능
'''

In [11]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])

In [93]:
print(x)
print(y)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [12]:
x+y

array([[ 6,  8],
       [10, 12]])

In [13]:
np.add(x, y)

array([[ 6,  8],
       [10, 12]])

In [14]:
x - y

array([[-4, -4],
       [-4, -4]])

In [15]:
np.subtract(x, y)

array([[-4, -4],
       [-4, -4]])

In [16]:
x*y

array([[ 5, 12],
       [21, 32]])

In [17]:
np.multiply(x,y)

array([[ 5, 12],
       [21, 32]])

In [18]:
x/y

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [19]:
np.divide(x,y)

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [20]:
x * x

array([[ 1,  4],
       [ 9, 16]])

In [21]:
np.sqrt(x)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [9]:
# 조건식도 가능 => 부울로 리턴
x == 2

In [22]:
y > 6

array([[False, False],
       [ True,  True]])

In [23]:
# 논리 연산도 가능
(x > 3) & (y > 6)

array([[False, False],
       [False,  True]])

In [34]:
# 인덱싱 정리
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]); a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [35]:
# 인덱스를 저장할 배열 생성
idx = np.array([0, 2, 0, 1]); idx

array([0, 2, 0, 1])

In [36]:
# 원본 배열 a의 각 행에서 인덱스에 일치하는 값 추출하기
a[np.arange(4), idx]

array([ 1,  6,  7, 11])

In [37]:
# 원본 배열 a의 각 행에서 인덱스에 일치하는 값 추출하면서 연산하기
b = a[np.arange(4), idx]*2
b

array([ 2, 12, 14, 22])

In [40]:
# 부울 인덱싱으로 추출 (정수 인덱싱처럼)
b = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]); b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
# 부울 인덱싱으로 짝수 구하기
bol = np.array([True, False, True, False, True, False, True, False, True, False])
b[bol]

array([0, 2, 4, 6, 8])

In [ ]:
'''
# 결측치 : 없다, 잘못된 데이터
# python : NaN(int), NULL(object)
# numpy : nan
'''

In [43]:
a = np.array([np.nan, 1, 2, np.nan, 3, 4, 5]); a

array([nan,  1.,  2., nan,  3.,  4.,  5.])

In [44]:
np.isnan(a)

array([ True, False, False,  True, False, False, False])

In [46]:
a[~np.isnan(a)]

array([1., 2., 3., 4., 5.])