In [ ]:
'''
# numpy 데이터 자료형
# dtype 속성에 해당 자료형 접두사 첫글자를 부여
 - b : bollean                 ex) dtype = 'b'
 - i : int(정수형)             ex) dtype = 'i8'  (64비트)
 - u : 보호없는 정수           ex) dtype = 'u8'  (64비트)
 - f : 부동소수점              ex) dtype = 'f8'  (64비트)
 - c : 복소수 부동소수점       ex) dtype = 'c16' (128비트)
 - O : 객체                    ex) dtype = 'O'   (객체에 대한 포인터)
 - S : 바이트 문자열           ex) dtype = '524' (24글자)
 - U : 유니코드 문자열         ex) dtype = 'U24' (24유니코드 글자)
 
 
 - Inf : 무한대
 - NaN (Not a Number)
 - N/A (Not avalible, not applicable)
 
 
'''

In [40]:
import numpy as np

In [41]:
# 자료형 지정은 값을 직접 집어넣거나 dtype 속성을 이용해서 지정할 수 있음
x = np.array([1,2,3])
x

array([1, 2, 3])

In [42]:
x.dtype

dtype('int32')

In [43]:
x = np.array([1,2,3.0])
x.dtype

dtype('float64')

In [44]:
x = np.array([1,2,3], dtype='int')
x.dtype

dtype('int32')

In [45]:
x = np.array([1,2,3], dtype='float')
x.dtype

dtype('float64')

In [46]:
y = np.array([1,2,3], dtype='f')
y.dtype

dtype('float32')

In [47]:
x = np.array([1,2,3], dtype='U')
x.dtype

dtype('<U1')

In [48]:
x[0] + x[1] #인덱싱한 값이 유니코드 문자임이 확인

'12'

In [49]:
np.array([0,1,-1,0])/np.array([1,0,0,0])

<ipython-input-49-dc768ac6b521>:1: RuntimeWarning: divide by zero encountered in true_divide
  np.array([0,1,-1,0])/np.array([1,0,0,0])
<ipython-input-49-dc768ac6b521>:1: RuntimeWarning: invalid value encountered in true_divide
  np.array([0,1,-1,0])/np.array([1,0,0,0])


array([  0.,  inf, -inf,  nan])

In [50]:
'''
# 배열 연결(concatenate)
 : 행의 수나, 열의 수가 같은 두 개 이상의 배열을 연결하여 더 큰 배열을 만들 때 사용하는 방법
 
 - hstack : 행의 수가 같은 두 개 이상의 배열을 옆으로 연결하여 열의 수가 더 많은 배열을 생성
          : 연결할 배열이 하나의 리스트에 담겨있어야 함
 - vstack : 열의 수가 같은 두 개 이상의 배열을 위아래로 연결하여 행의 수가 더 많은 배열을 생성
          : 연결할 배열이 하나의 리스트에 담겨있어야함
 - dstack : 깊이(depth)방향으로 배열을 연결

 - stack : dstack 확장버전
         : 배열이 겹쳐지듯이 확장되므로 연결하고자 하는 배열들의 크기가 모두 같아야 함
         : 인수로 axis를 사용할 수 있고 0~2까지 가능 
         
 - title : 동일한 배열을 반복해서 연결할 때 사용 (비슷한 명령을 repeat)
 
 
 
 - 특수 메소드(인덱서) : 메소드 이지만 ()을 사용하지 않음, 인덱싱과 같인 대괄호 []를 사용하므로 인덱서라고 지칭 
 - r_메소드 : hstack 과 비슷한 명령, 배열을 좌우로 연결 
 - c_메소드 : 배열의 차원을 증가시킨 후 좌우로 연결 
            : 그러므로 1차 배열을 연결하면 2차원 배열이 됨
  

'''

'\n# 배열 연결(concatenate)\n : 행의 수나, 열의 수가 같은 두 개 이상의 배열을 연결하여 더 큰 배열을 만들 때 사용하는 방법\n \n - hstack : 행의 수가 같은 두 개 이상의 배열을 옆으로 연결하여 열의 수가 더 많은 배열을 생성\n          : 연결할 배열이 하나의 리스트에 담겨있어야 함\n - vstack : 열의 수가 같은 두 개 이상의 배열을 위아래로 연결하여 행의 수가 더 많은 배열을 생성\n          : 연결할 배열이 하나의 리스트에 담겨있어야함\n - dstack : 깊이(depth)방향으로 배열을 연결\n\n - stack : dstack 확장버전\n         : 배열이 겹쳐지듯이 확장되므로 연결하고자 하는 배열들의 크기가 모두 같아야 함\n         : 인수로 axis를 사용할 수 있고 0~2까지 가능 \n'

In [51]:
a1 = np.ones((2,3)); a1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [52]:
a2 = np.zeros((2,2)); a2

array([[0., 0.],
       [0., 0.]])

In [53]:
# hstack
np.hstack([a1,a2])

array([[1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.]])

In [54]:
b1 = np.ones((2, 3)); b1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [55]:
b2 = np.zeros((3,3));b2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [56]:
# vstack
np.vstack([b1,b2])

array([[1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [57]:
c1 = np.ones((3,4)); c1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [58]:
c2 = np.zeros((3,4)); c2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [59]:
np.dstack([c1,c2])

array([[[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]]])

In [60]:
(np.dstack([c1,c2])).shape   # (깊이, 행, 열 )

(3, 4, 2)

In [61]:
# stack

In [62]:
c1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [63]:
c2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [64]:
np.stack([c1,c2])

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [67]:
(np.stack([c1,c2])).shape

(2, 3, 4)

In [66]:
# stack option
np.stack([c1,c2], axis=0)

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [68]:
np.stack([c1,c2], axis=1)

array([[[1., 1., 1., 1.],
        [0., 0., 0., 0.]],

       [[1., 1., 1., 1.],
        [0., 0., 0., 0.]],

       [[1., 1., 1., 1.],
        [0., 0., 0., 0.]]])

In [70]:
(np.stack([c1,c2], axis=1)).shape

(3, 2, 4)

In [71]:
(np.stack([c1,c2], axis=2)).shape

(3, 4, 2)

In [72]:
# 인덱서

In [73]:
r1 = np.array([1,2,3])
r2 = np.array([4,5,6])


In [75]:
np.r_[r1,r2]

array([1, 2, 3, 4, 5, 6])

In [78]:
np.r_[r2,r1]

array([4, 5, 6, 1, 2, 3])

In [79]:
# C_인덱서
r1 = np.array([1,2,3])
r2 = np.array([4,5,6])

In [80]:
np.c_[r1,r2]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [81]:
# title

In [85]:
t = np.array([[0,1,2],[11,12,13]]);t

array([[ 0,  1,  2],
       [11, 12, 13]])

In [86]:
np.tile(t,2)

array([[ 0,  1,  2,  0,  1,  2],
       [11, 12, 13, 11, 12, 13]])

In [87]:
# x,y 모두 반복 - tuple 적용
np.tile(t,(3,2))

array([[ 0,  1,  2,  0,  1,  2],
       [11, 12, 13, 11, 12, 13],
       [ 0,  1,  2,  0,  1,  2],
       [11, 12, 13, 11, 12, 13],
       [ 0,  1,  2,  0,  1,  2],
       [11, 12, 13, 11, 12, 13]])

In [92]:
# tile 비슷한 명령 : repeat

In [93]:
t2 = np.array([[1,2],[3,4]])
t2

array([[1, 2],
       [3, 4]])

In [94]:
np.repeat(t2,2)    # 요소에 있는 값을 그대로 반복 

array([1, 1, 2, 2, 3, 3, 4, 4])

In [95]:
np.tile(t2,2)

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

In [97]:
np.tile(t2, (2,1))

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

In [100]:
# repeat에도 axis 속성이 있음
print(np.repeat(t2,3))
print(np.repeat(t2,3, axis=1))
print(np.repeat(t2,3, axis=0))

[1 1 1 2 2 2 3 3 3 4 4 4]
[[1 1 1 2 2 2]
 [3 3 3 4 4 4]]
[[1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


In [101]:
'''
# 차원 축소(dimension reduction) 연산
ex) 1 2 3 4     ---> 평균 : 2.5
    5 6 4 7     ---> 평균 : 4

 : 행렬의 하나의 행에 있는 원소들을 데이터 집합으로 보고 그 집합의 평균을 구하면 각 집합당 하나의 값이 나오게 되고
   그럼 그 값들만 따로 데이터 집합으로 두면 차워 축소가 됨

> numpy에서 차원 축소 연산 명령 또는 메소드
  - 최대/최소 min,max, argnin(최소값 위치), argmax(최대값 위치)
  - 통계 : sum, mean, median, std, var
  - 참/거짓 : all, any
  
> axis 속성을 이용해면 어느 차원으로 계산을 할 지 지정할 수 잇으므로 대부분 차원축소 연산에 적용할 수 있음

'''

'\n# 차원 축소(dimension reduction) 연산\nex) 1 2 3 4     ---> 평균 : 2.5\n    5 6 4 7     ---> 평균 : 4\n\n : 행렬의 하나의 행에 있는 원소들을 데이터 집합으로 보고 그 집합의 평균을 구하면 각 집합당 하나의 값이 나오게 되고\n   그럼 그 값들만 따로 데이터 집합으로 두면 차워 축소가 됨\n\n> numpy에서 차원 축소 연산 명령 또는 메소드\n  - 최대/최소 min,max, argnin(최소값 위치), argmax(최대값 위치)\n  - 통계 : sum, mean, median, std, var\n  - 참/거짓 : all, any\n'

In [102]:
import numpy as np

In [103]:
x = np.array([1,10,100]); x

array([  1,  10, 100])

In [106]:
print(x.min())
print(x.argmin())

1
0


In [107]:
print(x.max())
print(x.argmax())

100
2


In [108]:
print(x.mean())
print(x.sum())
print(np.median(x))

37.0
111
10.0


In [109]:
# all : 배열의 모든 원소가 True 인지 평가하는 메소드
np.all([True,True,False])

False

In [110]:
# any : 배열에서 1개 이상의 원소가 True인지 평가하는 메소드
np.any([False,False,True,False])

True

In [111]:
# axis 
x = np.array([[1,1],[2,2]])
x

array([[1, 1],
       [2, 2]])

In [112]:
x.sum()

6

In [114]:
x.sum(axis=0)  # 열 합계

array([3, 3])

In [115]:
x.sum(axis=1)  #행 합계

array([2, 4])