# 난수(random number)

In [ ]:
'''
# 난수 발생 : np.rand() - 0부터 1사이의 실수
# seed(씨앗값) : 보통의 프로그래밍 언어는 난수값이 보통 설정되어있음
               : 조금 더 난수를 만들고 싶으면 씨앗값을 바꾸는 형태로 사용 
               
               
'''

In [1]:
import numpy as np

In [2]:
np.random.seed(0)
np.random.rand(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [3]:
np.random.rand(5)

array([0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152])

In [4]:
np.random.seed(0)
np.random.rand(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [5]:
np.random.seed(2)         # 시드를 바꾸면 그때그떄 다른 난수 가능
np.random.rand(5)

array([0.4359949 , 0.02592623, 0.54966248, 0.43532239, 0.4203678 ])

In [8]:
for i in range(10):
    print(np.random.rand())

0.505246090121704
0.06528650438687811
0.42812232759738944
0.09653091566061256
0.12715997170127746
0.5967453089785958
0.22601200060423587
0.10694568430998297
0.2203062070705597
0.34982628500329926


In [6]:
np.random.rand(10)

array([0.33033482, 0.20464863, 0.61927097, 0.29965467, 0.26682728,
       0.62113383, 0.52914209, 0.13457995, 0.51357812, 0.18443987])

In [7]:
# shuffle
x = np.arange(10)
print(x)
print('-----------------------------------')
np.random.shuffle(x)
print(x)

[0 1 2 3 4 5 6 7 8 9]
-----------------------------------
[5 0 8 3 4 9 1 2 6 7]


In [ ]:
'''
# 데이터 샘플링 : 이미 있는 데이터 집합에서 무작위로 선택하는 것 (sampling)
# np.random.choice (원본데이터, size, replace=True/False, p)

- 원본 데이터 : (range(원본데이터))
- size : 샘플 숫자
- replace : True이면 한 번 선택한 데이터를 다시 선택할 수 있음
- p : 각 데이터가 선택될 수 있는 확률
'''

In [9]:
x = np.random.choice(5, 5, replace=False); x

array([3, 4, 1, 2, 0])

In [13]:
x1 = np.random.choice(5, 3, replace=False); x1

array([2, 0, 3])

In [16]:
x2 = np.random.choice(5, 10, replace=False); x2

ValueError: Cannot take a larger sample than population when 'replace=False'

In [17]:
x2 = np.random.choice(5, 10, replace=True); x2     # 재사용을 하면 원본데이터보다 더 많은 값 추출 가능

array([4, 2, 3, 0, 3, 0, 2, 2, 0, 4])

In [18]:
x3 = np.random.choice(5, 10, replace=True, p=[0.1, 0, 0, 0.3, 0.6]); x3    # 요소별 선택 확률도 부여

array([4, 4, 4, 4, 4, 4, 0, 3, 4, 4])

In [ ]:
'''
# rand() : 0~1 실수 균일 분포
# randn() : 실수 가우시안 표준 정규 분포
# randint() : 균일분포 정수 - 난수
 - randint(low, high, size)
  -- size : 난수의 갯수
  
'''

In [19]:
np.random.rand(5)

array([0.02720237, 0.24717724, 0.06714437, 0.99385201, 0.97058031])

In [20]:
np.random.rand(3, 5)

array([[0.80025835, 0.60181712, 0.76495986, 0.16922545, 0.29302323],
       [0.52406688, 0.35662428, 0.04567897, 0.98315345, 0.44135492],
       [0.50400044, 0.32354132, 0.25974475, 0.38688989, 0.8320169 ]])

In [21]:
np.random.randn(10)

array([-0.72255835,  1.41621298,  0.57014127, -1.59014501, -0.06352438,
       -2.4417338 , -1.79591943, -1.02477173,  0.44430432,  0.04789425])

In [22]:
np.random.randint(10, 50, 5)

array([42, 49, 19, 24, 40])

In [29]:
# 로또 번호 6개 구해보세요
np.random.randint(1, 46, 6)

array([38, 10, 22, 37, 40, 41])

In [30]:
# 로또 5천원어치 구해보세요
np.random.randint(1, 46, (5,6))

array([[40, 20, 27, 37, 41, 39],
       [20,  9, 15, 28,  4, 16],
       [ 3, 23,  6,  6, 19, 38],
       [30, 13, 29,  7, 45,  6],
       [17,  6, 27, 20, 40, 38]])

In [31]:
# cf) 큰 값을 선언하지 않고 배열로 만드는 방법
np.empty((4, 3))

array([[1.07637373e-311, 3.16202013e-322, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 3.08861180e-057],
       [2.44748934e-056, 6.69902375e+170, 7.31785644e-042],
       [1.58865705e-076, 2.35991901e+184, 4.01646870e-057]])